### ISSUE TITLE
add-package failed

### ISSUE THREAD

**Issue by fanspace** [mholt/caddy-grpc-web#6]
caddy version v2.6.3
caddy add-package github.com/mholt/caddy-grpc-web
2023/02/09 03:21:57.741 INFO    this executable will be replaced        {"path": "D:\\caddy\\caddy.exe"}
2023/02/09 03:21:57.741 INFO    requesting build        {"os": "windows", "arch": "amd64", "packages": ["github.com/corazawaf/coraza-caddy", "github.com/mholt/caddy-grpc-web", "github.com/shift72/caddy-geo-ip"]}
Error: download failed: download failed: HTTP 400: unable to fulfill download request (id=0f7e7453-c089-4a92-85dd-a00e0d44db84)

**Comment by mholt** [comment]
Hmm, maybe a quirk with how I cleared the build cache. Can you try again?

**Comment by fanspace** [comment]
can not install yet 
caddy add-package github.com/mholt/caddy-grpc-web
2023/02/28 06:16:09.215 INFO    this executable will be replaced        {"path": "D:\\caddy\\caddy.exe"}
2023/02/28 06:16:09.215 INFO    requesting build        {"os": "windows", "arch": "amd64", "packages": ["github.com/mholt/caddy-grpc-web", "github.com/shift72/caddy-geo-ip", "github.com/corazawaf/coraza-caddy"]}
Error: download failed: secure request failed: Get "https://caddyserver.com/api/download?arch=amd64&os=windows&p=github.com%2Fmholt%2Fcaddy-grpc-web&p=github.com%2Fshift72%2Fcaddy-geo-ip&p=github.com%2Fcorazawaf%2Fcoraza-caddy": EOF

**Comment by mholt** [comment]
Try removing plugins one at a time, and wait for the response; if it succeeds, then perhaps that plugin is causing a problem. I'll have more time to look into it later -- in the meantime, you can use [xcaddy](https://github.com/caddyserver/xcaddy) to get a custom build :+1:
